Repository googleapis/java-core, pull requests merged in 2020-11, with the labels that each got.

#326 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#328 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#327 feat(test): add new MultipleAttemptRule, StdOutCaptureRule & StdErrCaptureRule JUnit 4 rules
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/MultipleAttemptsRule.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/StdErrCaptureRule.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/StdOutCaptureRule.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/StdXCaptureRule.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/StdXCaptureRuleTest.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/tests/MultipleAttemptsRuleTest.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/tests/StdErrCaptureRuleTest.java
  google-cloud-core/src/test/java/com/google/cloud/testing/junit4/tests/StdOutCaptureRuleTest.java
Labels: cla: yes

#334 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#338 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#339 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#341 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: automerge, cla: yes, context: full, samples
