Repository googleapis/java-core, pull requests merged in 2020-05, with the labels that each got.

#216 ci: enable GitHub actions
  .github/workflows/ci.yaml
  .kokoro/build.bat
  synth.metadata
Labels: automerge, cla: yes, context: full

#217 chore: update CONTRIBUTING.md to include code formatting
  CONTRIBUTING.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#222 deps: rely on shared-config for auto-value configuration
  google-cloud-core-grpc/pom.xml
  google-cloud-core-http/pom.xml
  google-cloud-core/EnableAutoValue.txt
  google-cloud-core/pom.xml
  pom.xml
Labels: cla: yes

#224 tests: clean up tests for IAM condition support
  google-cloud-core/src/test/java/com/google/cloud/PolicyV3Test.java
Labels: automerge, cla: yes
