Repository googleapis/java-core, pull requests merged in 2020-07, with the labels that each got.

#247 ci(java): run dependency test on Java 8 and 11
  .github/workflows/ci.yaml
  .kokoro/dependencies.sh
  synth.metadata
Labels: cla: yes, context: full

#258 fix: docs of com.google.cloud.Timestamp.parseTimestamp
  google-cloud-core/src/main/java/com/google/cloud/Timestamp.java
  google-cloud-core/src/test/java/com/google/cloud/TimestampTest.java
Labels: cla: yes

#264 chore(docs): add cloud-RAD
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
