Repository googleapis/java-core, pull requests merged in 2021-09, with the labels that each got.

#546 chore: remove readme autosynth config
  .kokoro/continuous/readme.cfg
Labels: cla: yes

#544 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, context: full

#548 chore(java): update windows build
  .github/readme/synth.py
  .github/trusted-contribution.yml
  .github/workflows/ci.yaml
  .kokoro/release/common.sh
  .kokoro/release/drop.sh
  .kokoro/release/promote.sh
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.sh
  .kokoro/release/stage.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, automerge, context: partial

#552 chore: remove linkage-monitor required check
  .github/sync-repo-settings.yaml
Labels: cla: yes

#551 chore: convert to owlbot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  google-cloud-core-bom/pom.xml
  owlbot.py
  synth.metadata
Labels: cla: yes, automerge

#562 deps: downgrading protobuf to 3.17.3
  pom.xml
Labels: cla: yes, automerge

#561 chore: relocate owl bot post processor
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
Labels: cla: yes

#570 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: cla: yes

#579 chore: change branch master to main in sync-repo-settings.yaml
  .github/sync-repo-settings.yaml
Labels: cla: yes

#580 chore: change branch master to main in github configurations
  README.md
Labels: cla: yes, automerge
