Repository googleapis/java-core, pull requests merged in 2021-03, with the labels that each got.

#389 deps: update io.grpc:grpc-bom to v1.36.0
  pom.xml
Labels: automerge, cla: yes

#398 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#400 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#401 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#409 chore(java): detect sample-secrets in build.sh
  .kokoro/build.sh
  synth.metadata
Labels: build.sh, cla: yes, context: full, in, sample-secrets, samples

#411 chore: remove staging bucket v2
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: automerge, cla: yes, context: full
