Repository googleapis/java-core, pull requests merged in 2021-02, with the labels that each got.

#368 deps: switch from Jackson to GSON
  google-cloud-core/pom.xml
  google-cloud-core/src/main/java/com/google/cloud/ServiceOptions.java
  google-cloud-core/src/test/java/com/google/cloud/ServiceOptionsTest.java
Labels: cla: yes

#367 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: cla: yes, context: partial

#369 build(java): run linkage monitor as GitHub action
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#371 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/auto-release.yaml
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#373 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#375 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#376 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#379 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#380 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#384 fix: fix gcloud SDK detection on Windows
  google-cloud-core/src/main/java/com/google/cloud/testing/BaseEmulatorHelper.java
Labels: automerge, cla: yes
