Repository googleapis/java-core, pull requests merged in 2022-04, with the labels that each got.

#795 feat: remove resource-config after relocation
  native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-core/resource-config.json
Labels: size: s

#794 feat: remove native-image.properties settings after relocation
  native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-core/native-image.properties
Labels: size: s

#793 feat(java): remove GoogleJsonClentFeature and OpenCensusFeature after relocation
  native-image-support/pom.xml
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/GoogleJsonClientFeature.java
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/clients/OpenCensusFeature.java
Labels: size: m

#771 feat(java): remove Netty Native Image configuration after relocation to gax
  native-image-support/pom.xml
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/GrpcNettyFeature.java
Labels: size: m

#807 feat: next release from main branch is 2.7.0
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: size: s

#808 ci: configure the protected branch
  .github/workflows/ci.yaml
  .github/workflows/downstream.yaml
Labels: automerge, size: l
