Repository googleapis/java-core, pull requests merged in 2022-05, with the labels that each got.

#820 feat(java): remove native-image-support module
  native-image-support/pom.xml
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/NativeImageUtils.java
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/clients/CloudFunctionsFeature.java
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/clients/CloudSqlFeature.java
  native-image-support/src/main/java/com/google/cloud/nativeimage/features/clients/SpannerFeature.java
  native-image-support/src/main/resources/META-INF/native-image/com.google.cloud/google-cloud-core/native-image.properties
  pom.xml
Labels: size: l

#822 fix: remove native-image-support module from version.txt
  versions.txt
Labels: size: xs

#832 chore: remove native-image-support from bom
  google-cloud-core-bom/pom.xml
Labels: automerge, size: xs
